
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 10 13:37:29 EST 2013
//----------------------------------------------------

package fractal.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOUBLE = 36;
  public static final int INTEGER = 35;
  public static final int LPAREN = 16;
  public static final int RENDER = 10;
  public static final int FORWARD = 2;
  public static final int MINUS = 22;
  public static final int LEVEL = 11;
  public static final int RPAREN = 17;
  public static final int NOT = 32;
  public static final int AND = 33;
  public static final int LT = 29;
  public static final int OR = 34;
  public static final int COMMA = 18;
  public static final int DIV = 24;
  public static final int PLUS = 21;
  public static final int ASSIGN = 26;
  public static final int FRACTAL = 7;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SELF = 9;
  public static final int MUL = 23;
  public static final int HOME = 5;
  public static final int MOD = 25;
  public static final int EQ = 31;
  public static final int LBRACE = 19;
  public static final int VARIABLE = 37;
  public static final int COMPOSE = 27;
  public static final int SCALE = 12;
  public static final int SAVE = 14;
  public static final int CLEAR = 6;
  public static final int RBRACE = 20;
  public static final int END = 8;
  public static final int DEF = 13;
  public static final int SEQUENCE = 28;
  public static final int BACK = 3;
  public static final int RIGHT = 4;
  public static final int RESTORE = 15;
  public static final int GT = 30;
}

