package fractal.syntax;

import fractal.semantics.Visitor;
import fractal.sys.FractalException;

/**
  Class ASTSetLevel.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTSetLevel extends ASTStatement {
  ASTExp level;

  public ASTSetLevel (ASTExp level) {
    this.level = level;
  }

  public ASTExp getLevel() {
    return level;
  }

  @Override
  public <S, T> T visit(Visitor<S, T> v, S state) throws FractalException {
    return v.visitASTSetLevel(this, state);
  }

}
