package fractal.syntax;

import fractal.semantics.Visitor;
import fractal.sys.FractalException;

/**
  Class ASTSetScale.
  Intermediate representation class autogenerated by CS34Q semantic generator.
  Created on Sat Oct 12 03:13:16 2013
*/
public class ASTSetScale extends ASTStatement {
  ASTExp scale;

  public ASTSetScale (ASTExp scale) {
    this.scale = scale;
  }

  public ASTExp getScale() {
    return scale;
  }

  @Override
  public <S, T> T visit(Visitor<S, T> v, S state) throws FractalException {
    return v.visitASTSetScale(this, state);
  }

}
