package fractal.syntax;

import fractal.semantics.Visitor;
import fractal.sys.FractalException;

/**
 * Class ASTTCmdRight. Intermediate representation class autogenerated by CS34Q
 * semantic generator. Created on Sat Oct 12 03:13:16 2013
 */
public class ASTTCmdRight extends ASTTurtleCmd {
	ASTExp angle;

	public ASTTCmdRight(ASTExp angle) {
		this.angle = angle;
    System.out.print(angle);
	}

	public ASTExp getAngle() {
		return angle;
	}

	@Override
	public <S, T> T visit(Visitor<S, T> v, S state) throws FractalException {
		return v.visitASTTCmdRight(this, state);
	}

	@Override
	public String toString() {
		return "RIGHT " + this.angle.toString();
	}

}
