
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 18 18:44:36 EST 2013
//----------------------------------------------------

package fractal.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PENDOWN = 18;
  public static final int INTEGER = 36;
  public static final int LPAREN = 19;
  public static final int RENDER = 11;
  public static final int FORWARD = 2;
  public static final int MINUS = 25;
  public static final int LEVEL = 12;
  public static final int RPAREN = 20;
  public static final int NOT = 33;
  public static final int AND = 34;
  public static final int LT = 30;
  public static final int OR = 35;
  public static final int COMMA = 21;
  public static final int DIV = 27;
  public static final int PLUS = 24;
  public static final int FRACTAL = 8;
  public static final int LEFT = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int SELF = 10;
  public static final int MUL = 26;
  public static final int HOME = 6;
  public static final int EQ = 32;
  public static final int REAL = 37;
  public static final int LBRACE = 22;
  public static final int VARIABLE = 38;
  public static final int COMPOSE = 28;
  public static final int SCALE = 13;
  public static final int SAVE = 15;
  public static final int CLEAR = 7;
  public static final int RBRACE = 23;
  public static final int PENUP = 17;
  public static final int END = 9;
  public static final int DEF = 14;
  public static final int SEQUENCE = 29;
  public static final int BACK = 3;
  public static final int RIGHT = 4;
  public static final int RESTORE = 16;
  public static final int GT = 31;
}

